package testCases;

import org.openqa.selenium.Alert;
import org.openqa.selenium.NoAlertPresentException;
import org.testng.Assert;
import org.testng.annotations.Test;

import pageObject.HomePage;
import pageObject.Login;
import testBase.BaseClass;
import utilities.DataProviders;

public class TC003_Login_TestDDT extends BaseClass {

	@Test(dataProvider = "loginData", dataProviderClass = DataProviders.class) // getting data provider from different
																				// class
	public void verify_Login_with_DDT(String uname, String pword, String exp) throws InterruptedException {
		try {
			// Home page
			HomePage hp = new HomePage(driver);
			hp.click_on_Login_link();
			// login pop up
			Login lp = new Login(driver);
			lp.enter_Username(uname);
			lp.enter_Password(pword);
			lp.click_on_Login();
			Thread.sleep(3000);
			boolean lnkLogout = lp.logout_link_display();
			System.out.println(lnkLogout);
			
			if (exp.equalsIgnoreCase("valid")) {

				if (lnkLogout == true) {
					lp.click_on_Logout();
					System.out.println("out");
					
				}
			} else {
				lp.click_on_Close();
							}
			if (exp.equalsIgnoreCase("Invalid")) {

				if (lnkLogout == true) {
					lp.click_on_Logout();
					System.out.println("out");
					
				}
			} else {
				try {
					Alert a = driver.switchTo().alert();

					a.accept();

				} catch (NoAlertPresentException e) {
					System.out.println("No alert found");
				}
				lp.click_on_Close();
				
			}

		} catch (Exception e) {
						System.out.println(e);
		}
	}
}
